// File generated by flutterfire_cli - run `flutterfire configure` to generate actual file
// Or manually create this file with your Firebase project configuration

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnG8Tubk9ZHnjbE5ORUJ1Av9U2R-G3FDc',
    appId: '1:922607034589:web:5650f921266bcd19f0fb34',
    messagingSenderId: '922607034589',
    projectId: 'expensify-468da',
    authDomain: 'expensify-468da.firebaseapp.com',
    storageBucket: 'expensify-468da.firebasestorage.app',
    measurementId: 'G-YMJQ98RB15',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzQ3AgW2WG0RtWp46nZr9oFPoS4ZE8D3A',
    appId: '1:922607034589:android:bb106ee95d300f2ff0fb34',
    messagingSenderId: '922607034589',
    projectId: 'expensify-468da',
    storageBucket: 'expensify-468da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzDyi62CL5l2vjnvUoIUoCxnuTXx42Jgc',
    appId: '1:922607034589:ios:10d57dddae057020f0fb34',
    messagingSenderId: '922607034589',
    projectId: 'expensify-468da',
    storageBucket: 'expensify-468da.firebasestorage.app',
    iosBundleId: 'com.expensify.expensify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzDyi62CL5l2vjnvUoIUoCxnuTXx42Jgc',
    appId: '1:922607034589:ios:10d57dddae057020f0fb34',
    messagingSenderId: '922607034589',
    projectId: 'expensify-468da',
    storageBucket: 'expensify-468da.firebasestorage.app',
    iosBundleId: 'com.expensify.expensify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnG8Tubk9ZHnjbE5ORUJ1Av9U2R-G3FDc',
    appId: '1:922607034589:web:a914bedd0f2ccc42f0fb34',
    messagingSenderId: '922607034589',
    projectId: 'expensify-468da',
    authDomain: 'expensify-468da.firebaseapp.com',
    storageBucket: 'expensify-468da.firebasestorage.app',
    measurementId: 'G-GN1SJLH3RE',
  );

}